default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies:
      - "flake8-builtins"
      - "flake8-implicit-str-concat"
      - "flake8-no-pep420"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: check-yaml
      exclude: mkdocs.yml
    - id: check-yaml
      name: check-yaml-mkdocs
      # --unsafe is a workaround for the use of !! in mkdocs.yml.
      args: [--unsafe]
      files: mkdocs.yml
    - id: detect-private-key
