default_language_version:
  python: python3.11

repos:
  - repo: local
    hooks:
    - id: check
      name: check
      entry: just check
      language: system
      types: [python]
      require_serial: true
      pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: check-yaml
      exclude: mkdocs.yml
    - id: check-yaml
      name: check-yaml-mkdocs
      # --unsafe is a workaround for the use of !! in mkdocs.yml.
      args: [--unsafe]
      files: mkdocs.yml
    - id: detect-private-key
