site_name: OpenSAFELY documentation
site_url: !ENV MKDOCS_SITE_URL
repo_url: https://github.com/opensafely/documentation

nav:
  - Introduction: index.md
  - About OpenSAFELY:
      - Our philosophy: open-methods.md
      - Security: security-levels.md
      - Access policies: access-policies.md
      - Technical architecture: technical-architecture.md
      - Contributing: contributing.md
  - Getting Started guide: getting-started.md
  - Using OpenSAFELY:
      - Analysis workflow: workflow.md
      - Federated analytics: federation.md
      - GitHub repositories: repositories.md
      - Data sources:
          - data-sources/index.md
          - Overview: data-sources/intro.md
          - SystmOne primary care: data-sources/systmone.md
          - EMIS primary care: data-sources/emis.md
          - Covid-19 infection survey: data-sources/onscis.md
          - Covid-19 test results: data-sources/sgsscovid.md
          - Covid-19 therapeutics: data-sources/therapeutics.md
          - Emergency attendances: data-sources/ecds.md
          - High Cost Drugs: data-sources/hcd.md
          - Hospital admissions: data-sources/apc.md
          - In-hospital deaths (covid-19 only): data-sources/cpns.md
          - Intensive care admissions (covid-19 only): data-sources/icnarc.md
          - International Severe Acute Respiratory and emerging Infection Consortium: data-sources/isaric.md
          - Registered deaths: data-sources/onsdeaths.md
          - UK Renal Registry: data-sources/ukrr.md
      - Detailed installation guides:
          - Overview: install-intro.md
          - Managing Gitpod workspaces: gitpod-workspaces.md
          - GitHub and Git: install-github-and-git.md
          - Python: install-python.md
          - Docker: install-docker.md
          - OpenSAFELY CLI: opensafely-cli.md
          - macOS: install-macos.md
          - Linux: install-linux.md
      - Study definitions:
          - Overview: study-def.md
          - Working with dates: study-def-dates.md
          - Working with codelists: study-def-codelists.md
          - Dummy data and expectations: study-def-expectations.md
          - Variable reference: study-def-variables.md
          - Measures: measures.md
          - Create inclusion/exclusion flowcharts: study-def-flowcharts.md
          - Programming tricks: study-def-tricks.md
      - Codelists:
          - Introduction to codelists: codelist-intro.md
          - Building a codelist: codelist-creation.md
          - Adding codelists to a project: codelist-project.md
          - SNOMED CT codelists: codelist-snomed.md
      - Actions:
          - Overview: actions-intro.md
          - The project pipeline: actions-pipelines.md
          - The cohortextractor action: actions-cohortextractor.md
          - Scripted actions: actions-scripts.md
          - Reusable actions: actions-reusable.md
      - Jobs site: jobs-site.md
      - Level 4 server: level-4-server.md
      - Safe Outputs and requesting release of files from the Level 4 server: releasing-files.md
      - Reports:
        - Overview: reports/intro.md
        - Create a draft: reports/create-a-draft.md
        - Review process: reports/review-process.md
        - Publishing a report: reports/publish-a-report.md
      - Project completion: project-completion.md
      - Adding your pre-print/paper to OpenSAFELY.org: adding-a-paper.md
      - Information for system integrators: system-integration.md
  - OpenSAFELY best practice:
      - Bennett Institute Open Manifesto: open-data-manifesto.md
      - Developing a protocol: protocol.md
      - Using Git effectively: git-workflow.md
      - Code reviews: code-reviews.md
      - Case-control studies: case-control-studies.md
      - Writing performant code: memory-efficient-working.md
  - ehrQL: '!import https://github.com/opensafely-core/ehrql?branch=main'
  - Support:
      - How to get help: how-to-get-help.md
      - OpenSAFELY co-piloting service: copiloting-service.md
      - Requesting new libraries: requesting-libraries.md
      - Requesting study definition variables: requesting-variables.md
      - Plan S and OpenSAFELY: plan-s.md
      - Updating the documentation: updating-the-docs.md
  - Platform News: https://www.opensafely.org/changelog/
theme:
  name: material
  font: false
  logo: img/icon.svg
  favicon: img/favicon.svg
  palette:
    scheme: opensafely
  custom_dir: overrides
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.expand

edit_uri: "edit/main/docs/"

extra_css:
  - css/youtube.css
  - css/extra.css
  - ehrql/stylesheets/extra.css

extra_javascript:
  - js/extra.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/opensafely
      name: OpenSAFELY on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/opensafely
      name: OpenSAFELY on Twitter
  # Import ehrQL docs from a specified branch (defaults to main)
  # see hooks/ehrql_branch.py
  ehrql_branch: !ENV [EHRQL_BRANCH, "main"]
  ehrql_imported_css:
    - imported_docs/ehrql/stylesheets/extra.css

copyright: © University of Oxford for the Bennett Institute for Applied Data Science. This work may be copied freely for non-commercial research and study. If you wish to do any of the other acts restricted by the copyright you should apply in writing to bennett@phc.ox.ac.uk.

plugins:
  - search
  - table-reader:
      data_path: imported_docs/ehrql
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: false
            show_source: false
            show_if_no_docstring: true
            heading_level: 4
          paths: [src/cohort-extractor]
      custom_templates: templates
  - macros
  - multirepo:
      cleanup: !ENV [MKDOCS_MULTIREPO_CLEANUP, false]
      temp_dir: imported_docs

watch:
  - includes
  - src/cohort-extractor/cohortextractor

markdown_extensions:
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
      base_path: # base paths will be checked in order for matching snippets
        - .  # dir containing this config file
        - imported_docs/ehrql # docs folder for the imported repo
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "🔗"
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - admonition
  - footnotes
  - abbr
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

hooks:
    - hooks/parent_snippets.py
    - hooks/ehrql_branch.py
    - hooks/ehrql_css.py
