site_name: OpenSAFELY documentation
site_url: !ENV MKDOCS_SITE_URL
repo_url: https://github.com/opensafely/documentation

exclude_docs: |
  /ehrql/includes/generated_docs/

nav:
  - Introduction: index.md
  - About OpenSAFELY:
      - Our philosophy: open-methods.md
      - Security: security-levels.md
      - "Safe data access: The Five Safes": five-safes.md
      - Access policies: access-policies.md
      - Technical architecture: technical-architecture.md
      - Type One Opt Outs: type-one-opt-outs.md
      - Contributing: contributing.md
  - Getting started:
      - Getting started: getting-started/index.md
      - Tutorial:
        - Tutorial: getting-started/tutorial/index.md
      - How-to guides:
        - How-to guides: getting-started/how-to/index.md
      - Explanation:
        - Explanation: getting-started/explanation/index.md
  - Using OpenSAFELY:
      - Analysis workflow: workflow.md
      - Federated analytics: federation.md
      - GitHub repositories: repositories.md
      - Codelists:
          - Introduction to codelists: codelist-intro.md
          - Building a codelist: codelist-creation.md
          - Adding codelists to a project: codelist-project.md
          - Keeping codelists up to date: codelist-updating.md
      - Actions:
          - Overview: actions-intro.md
          - The project pipeline: actions-pipelines.md
          - Scripted actions: actions-scripts.md
          - Reusable actions: actions-reusable.md
      - Jobs site: jobs-site.md
      - Level 4 server: level-4-server.md
      - Releasing research outputs from the Level 4 server:
        - Overview: releasing-files-intro.md
        - Applying statistical disclosure control: sdc.md
        - Requesting release of research outputs: requesting-file-release.md
        - Review process for release requests: output-checking.md
        - Release of approved outputs: releasing-files.md
        - Releasing with Airlock: '!import https://github.com/opensafely-core/airlock?branch=main'
      - Reports:
        - Overview: reports/intro.md
        - Create a draft: reports/create-a-draft.md
        - Review process: reports/review-process.md
        - Publishing a report: reports/publish-a-report.md
      - Managing your OpenSAFELY project:
        - Telling us about changes to your project: project-changes.md
        - Project completion: project-completion.md
      - Adding your pre-print/paper to OpenSAFELY.org: adding-a-paper.md
      - Information for system integrators: system-integration.md
      - Legacy:
        - Study definitions:
          - Overview: study-def.md
          - Working with dates: study-def-dates.md
          - Working with codelists: study-def-codelists.md
          - Dummy data and expectations: study-def-expectations.md
          - Variable reference: study-def-variables.md
          - Measures: measures.md
          - Create inclusion/exclusion flowcharts: study-def-flowcharts.md
          - Programming tricks: study-def-tricks.md
  - OpenSAFELY best practice:
      - Developing a protocol: protocol.md
      - Using Git effectively: git-workflow.md
      - Code reviews: code-reviews.md
      - Case-control studies: case-control-studies.md
      - Writing performant code: memory-efficient-working.md
  - ehrQL: '!import https://github.com/opensafely-core/ehrql?branch=main'
  - Data sources:
      - data-sources/index.md
      - Overview: data-sources/intro.md
      - SystmOne primary care: data-sources/systmone.md
      - EMIS primary care: data-sources/emis.md
      - Covid-19 test results: data-sources/sgsscovid.md
      - Covid-19 therapeutics: data-sources/therapeutics.md
      - Emergency attendances: data-sources/ecds.md
      - High Cost Drugs: data-sources/hcd.md
      - Hospital admissions: data-sources/apc.md
      - In-hospital deaths (covid-19 only): data-sources/cpns.md
      - Intensive care admissions (covid-19 only): data-sources/icnarc.md
      - International Severe Acute Respiratory and emerging Infection Consortium: data-sources/isaric.md
      - Registered deaths: data-sources/onsdeaths.md
      - UK Renal Registry: data-sources/ukrr.md
  - Support:
      - How to get help: how-to-get-help.md
      - OpenSAFELY co-piloting service: copiloting-service.md
      - Requesting new libraries: requesting-libraries.md
      - Plan S and OpenSAFELY: plan-s.md
      - Updating the documentation: updating-the-docs.md
  - Bennett Institute Open Manifesto: open-data-manifesto.md
  - Platform News: https://www.opensafely.org/changelog/
theme:
  name: material
  font: false
  logo: img/icon.svg
  favicon: img/favicon.svg
  palette:
    scheme: opensafely
  custom_dir: overrides
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.indexes

edit_uri: "edit/main/docs/"

extra_css:
  - css/youtube.css
  - css/extra.css
  - css/lite-yt-embed.css
  - ehrql/stylesheets/extra.css

extra_javascript:
  - js/extra.js
  - js/lite-yt-embed.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/opensafely
      name: OpenSAFELY on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/opensafely
      name: OpenSAFELY on Twitter
  # Import ehrQL docs from a specified branch (defaults to main)
  # see hooks/ehrql_branch.py
  ehrql_branch: !ENV [EHRQL_BRANCH, "main"]
  ehrql_imported_css:
    - imported_docs/ehrql/stylesheets/extra.css

copyright: © University of Oxford for the Bennett Institute for Applied Data Science. This work may be copied freely for non-commercial research and study. If you wish to do any of the other acts restricted by the copyright you should apply in writing to bennett@phc.ox.ac.uk.

plugins:
  - search
  - table-reader:
      data_path: imported_docs/ehrql
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: false
            show_source: false
            show_if_no_docstring: true
            heading_level: 4
          paths: [src/cohort-extractor]
      custom_templates: templates
  - macros
  - multirepo:
      cleanup: !ENV [MKDOCS_MULTIREPO_CLEANUP, false]
      temp_dir: imported_docs

watch:
  - includes
  - src/cohort-extractor/cohortextractor

markdown_extensions:
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
      base_path: # base paths will be checked in order for matching snippets
        - .  # dir containing this config file
        - imported_docs/ehrql # docs folder for the imported repo
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "🔗"
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: ehrql
          lang: python
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - admonition
  - footnotes
  - abbr
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

hooks:
    - hooks/parent_snippets.py
    - hooks/ehrql_branch.py
    - hooks/ehrql_css.py
