services:
  - type: web
    name: opensafely-documentation
    env: static
    buildCommand: mkdocs build
    staticPublishPath: ./site
    pullRequestPreviewsEnabled: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    routes:
      - type: redirect
        source: /en
        destination: /
      - type: redirect
        source: /en/stable
        destination: /
      - type: redirect
        source: /en/stable/codelist_creation
        destination: /codelist-creation/
      - type: redirect
        source: /en/stable/getting_started_checklist
        destination: /getting-started/
      - type: redirect
        source: /en/stable/onboarding_analysts
        destination: /
      - type: redirect
        source: /en/stable/open_data_manifesto
        destination: /open-data-manifesto/
      - type: redirect
        source: /en/stable/snomed
        destination: /codelist-snomed/
      - type: redirect
        source: /en/stable/study_definition
        destination: /study-def/
      - type: redirect
        source: /en/latest
        destination: /
      - type: redirect
        source: /en/latest/:path
        destination: /:path
      - type: redirect
        source: /en/stable/:path
        destination: /:path
      - type: redirect
        source: /news
        destination: https://www.opensafely.org/changelog/
      - type: redirect
        source: /dataset-intro
        destination: /data-sources/intro/
      - type: redirect
        source: /dataset-systmone
        destination: /data-sources/systmone/
      - type: redirect
        source: /dataset-emis
        destination: /data-sources/emis/
      - type: redirect
        source: /dataset-onscis
        destination: /data-sources/onscis/
      - type: redirect
        source: /dataset-sgsscovid
        destination: /data-sources/sgsscovid/
      - type: redirect
        source: /dataset-therapeutics
        destination: /data-sources/therapeutics/
      - type: redirect
        source: /dataset-ecds
        destination: /data-sources/ecds/
      - type: redirect
        source: /dataset-apc
        destination: /data-sources/apc/
      - type: redirect
        source: /dataset-cpns
        destination: /data-sources/cpns/
      - type: redirect
        source: /dataset-icnarc
        destination: /data-sources/icnarc/
      - type: redirect
        source: /dataset-isaric
        destination: /data-sources/isaric/
      - type: redirect
        source: /dataset-onsdeaths
        destination: /data-sources/onsdeaths/
      - type: redirect
        source: /dataset-ukrr
        destination: /data-sources/ukrr/
