version: "3.0"

expectations:
  population_size: 3000

actions:
  extract_minimal_cohort:
    run: databuilder:v0 generate-dataset "./1a_minimal_dataset_definition.py" --dsn "example-data/minimal"
    outputs:
      highly_sensitive:
        cohort: outputs/1a_minimal_dataset_definition.csv
