---
name: 'Check links'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: '37 11 * * 2'

permissions:
  contents: read

jobs:

  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Python and just
        uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: '3.11'

      - name: Build site
        env:
          AccessToken: ${{ secrets.GITHUB_TOKEN }}
          MKDOCS_SITE_URL: https://docs.opensafely.org
          EHRQL_BRANCH: main
        run: just build

      - name: Move imported documentation to correct relative path
        run: mv imported_docs/* docs/

      - name: Check links
        uses: lycheeverse/lychee-action@ec3ed119d4f44ad2673a7232460dc7dff59d2421  # v1.8.0
        with:
          args: "--exclude-all-private --exclude-mail --include-verbatim --require-https --verbose --no-progress --timeout 60 './docs/**/*.md' './docs/**/*.html', './imported_docs/**/*.md' './imported_docs/**/*.html'"
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: "Notify Slack on Failure"
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@3665186a8c1a022b28a1dbe0954e73aa9081ea9e # v1.6.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel_id: C03FB777L1M
          status: "Check Docs Links Failure"
          color: danger
