---
name: 'Check links'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: '12 10 * * 2'

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check links
        uses: lycheeverse/lychee-action@4dcb8bee2a0a4531cba1a1f392c54e8375d6dd81  # v1.5.4
        with:
          args: "--exclude-all-private --exclude-mail --include-verbatim --require-https --verbose --no-progress './**/*.md' './**/*.html'"
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
