---
name: Check code snippets

on:
  pull_request:

jobs:
  snippets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: "pip"
          cache-dependency-path: databuilder/requirements.*.txt

      - uses: extractions/setup-just@v1

      - name: Run dev tooling on snippets
        run: just databuilder/check

      - name: Check dataset definitions run with Python installed Data Builder
        run: just databuilder/check-dataset-definitions

      - name: Check dataset definition outputs are up-to-date
        run: just databuilder/check-dataset-definitions-outputs-are-current

      - name: Check snippets work
        run: |
          # extract examples from the snippets, this will also test they are
          # valid examples
          just databuilder/extract

          # check no examples have changed
          git diff --exit-code examples

      - name: Install OpenSAFELY CLI
        run: pip install opensafely

      - name: Check dataset definitions outputs can be built with OpenSAFELY CLI
        run: just databuilder/build-dataset-definitions-outputs-docker
