on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python3 -m pip install -r ./requirements.txt

      - name: Build site
        run: mkdocs build

      - name: Add a version file
        run: echo ${{ github.sha }} > site/version.html

      - name: Publish
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: cloudflare/pages-action@c4f0d2e08d902c9cdfe3cdf854896c6f363ae5be  # v1.1.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          directory: "site"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: "opensafely-docs"
